### PR TITLE
list graph.nodes for py3 compatibility

### PR DESCRIPTION
**Pull request by LinguList**
as I'm using py3, and networkx now has generators, graph.nodes() should be list(graph.nodes()). With this patch, the simulation runs fine for me.

### CODE REVIEW

**Comment by Anaphory** [comment]
Python 3 is my default python, as well, but anyway.

**Comment by LinguList** [comment]
maybe it's the networkx version: they changed that recently. do you use py3.5, or earlier?

**Comment by Anaphory** [comment]
The computer I did that development on is in the office, so I can't check right now. I thought I installed most python things newly in Poznań, because the laptop is still somewhat new and not thoroughly configured, I'll have to check on Monday.

**Comment by Anaphory** [comment]
Side note: Shouldn't the Travis CI daemon have put a comment in here that your PR does not break the existing tests?

**Comment by LinguList** [comment]
I think there was some comment, but it disappeared. Is that possible?

**Pull request merged**
