### PR TITLE
hope this passes the tests

### PR DESCRIPTION
**Pull request by LinguList**
I have an assertion error in pytest on my machine in test_simulation:test_random_speaker and test_random_speaker_among, but I don't see why (the k*0.9 line). 

For the rest, I also checked pep8 this time, and I hope it's fine.

I added a command-line, so running

```shell
$ phylo run
```
runs the simulation. Idea from @xrotwang, and I find it quite useful, as one can quickly test things without having to go through the terminal of python.

### CODE REVIEW

**Comment by Anaphory** [comment]
Given that some tests are stochastic, they sometimes fail randomly – that may be what happened here. This sounds particulary likely given that travis hasn't complained.

**Comment by LinguList** [comment]
maybe, using a seed-parameter, would help to capture that. I also didn't
consider that before, but for testing, seeding seems like the things
that is usually recommended, isn't it?

**Comment by Anaphory** [comment]
That depends on what you test. In this case, I want to test an average, and a seed would (a) not be stable (if I change the implementation, swapping to random generators around or putting one in a conditional clause or whatever) and (b) not test what I want to test, which is that the system generally behaves as intended.

If you have a simulation and want to make it reproduceable, you have to supply a seed.

For my model, the goal is to pass a RandomGenerator around between functions which is initialized by a user-supplied seed once, precisely for reproduceabililty. But I think I still use two random, not numpy.random, in some places, which needs cleanup.

**Comment by LinguList** [comment]
I see. I was too my shame never really working with any seeds, but I
also did not too often work with randomization...

**Comment by LinguList** [comment]
cool, curious to test it out later.

**Pull request merged**
